FloripaSat-EPS: timer.c File Reference
timer.c File Reference
#include <msp430.h>
#include <stdlib.h>
#include <stdio.h>
#include <intrinsics.h>
#include "watchdog.h"
#include "ADS1248.h"
#include "pid.h"
#include "hal.h"
#include "ADC.h"
#include "timer.h"
#include "I2C.h"
#include "onewire.h"
#include "uart.h"
#include "mppt.h"
#include "energy_level_algorithm.h"
#include "fsp.h"
Functions
__interrupt void timer0_a0_isr (void)
__interrupt void timer0_a1_isr (void)
void timer_config (void)
Variables
volatile uint8_t EPS_data [70]
Function Documentation
timer0_a0_isr()
__interrupt void timer0_a0_isr (void)
Definition at line 25 of file timer.c.
References accumulated_current_LSB_register, accumulated_current_MSB_register, accumulated_current_unit, adc_read(), average_current_LSB_register, average_current_MSB_register, battery1_voltage_LSB, battery1_voltage_MSB, battery2_voltage_LSB, battery2_voltage_MSB, battery_accumulated_current_LSB, battery_accumulated_current_MSB, battery_average_current_LSB, battery_average_current_MSB, battery_current_LSB, battery_current_MSB, battery_monitor_temeperature_LSB, battery_monitor_temeperature_MSB, beacon_eps_current, beacon_eps_current_LSB, beacon_eps_current_MSB, bus_voltage, bus_voltage_LSB, bus_voltage_MSB, current_LSB_register, current_MSB_register, current_unit, DS2775_read_register(), energyLevelAlgorithm(), EPS_data, eps_status, float_send(), msp_temperature, msp_temperature_LSB, msp_temperature_MSB, negative_x_panel_current_LSB, negative_x_panel_current_MSB, negative_x_positive_z_panel_voltage_LSB, negative_x_positive_z_panel_voltage_MSB, negative_y_panel_current_LSB, negative_y_panel_current_MSB, negative_y_positive_x_panel_voltage_LSB, negative_y_positive_x_panel_voltage_MSB, negative_z_panel_current_LSB, negative_z_panel_current_MSB, negative_z_positive_y_panel_voltage_LSB, negative_z_positive_y_panel_voltage_MSB, Pid_Control(), positive_x_panel_current_LSB, positive_x_panel_current_MSB, positive_y_panel_current_LSB, positive_y_panel_current_MSB, positive_z_panel_current_LSB, positive_z_panel_current_MSB, protection_register, protection_register_LSB, read_ADS1248(), RTD0_B1, RTD0_B2, RTD0_B3, RTD1_B1, RTD1_B2, RTD1_B3, RTD2_B1, RTD2_B2, RTD2_B3, RTD3_B1, RTD3_B2, RTD3_B3, RTD4_B1, RTD4_B2, RTD4_B3, RTD5_B1, RTD5_B2, RTD5_B3, RTD6_B1, RTD6_B2, RTD6_B3, temperature_LSB_register, temperature_MSB_register, timer_debug_pin_1s, timer_debug_port_1s, uart_tx_beacon(), uart_tx_debug(), voltage_LSB1_register, voltage_LSB2_register, voltage_MSB1_register, voltage_MSB2_register, voltage_unit, vpanels_voltage, vpanels_voltage_LSB, vpanels_voltage_MSB, and watchdog_reset_counter().
timer0_a1_isr()
__interrupt void timer0_a1_isr (void)
Definition at line 333 of file timer.c.
References adc_read(), EPS_data, float_send(), mppt_algorithm(), negative_x_panel_current, negative_x_panel_current_LSB, negative_x_panel_current_MSB, negative_x_positive_z_panel_voltage, negative_x_positive_z_panel_voltage_LSB, negative_x_positive_z_panel_voltage_MSB, negative_y_panel_current, negative_y_panel_current_LSB, negative_y_panel_current_MSB, negative_y_positive_x_panel_voltage, negative_y_positive_x_panel_voltage_LSB, negative_y_positive_x_panel_voltage_MSB, negative_z_panel_current, negative_z_panel_current_LSB, negative_z_panel_current_MSB, negative_z_positive_y_panel_voltage, negative_z_positive_y_panel_voltage_LSB, negative_z_positive_y_panel_voltage_MSB, positive_x_panel_current, positive_x_panel_current_LSB, positive_x_panel_current_MSB, positive_y_panel_current, positive_y_panel_current_LSB, positive_y_panel_current_MSB, positive_z_panel_current, positive_z_panel_current_LSB, positive_z_panel_current_MSB, timer_debug_pin_100ms, timer_debug_port_100ms, uart_tx_debug(), and watchdog_reset_counter().
timer_config()
void timer_config (void)
Definition at line 526 of file timer.c.
References timer_debug_pin_100ms, timer_debug_pin_1s, and timer_debug_port_dir.
Referenced by config_msp430().
Variable Documentation
EPS_data
volatile uint8_t EPS_data[70]
Definition at line 7 of file I2C.c.
Referenced by timer0_a0_isr(), timer0_a1_isr(), and USCI_B2_ISR().