FloripaSat-EPS: watchdog.c File Reference
watchdog.c File Reference
#include "watchdog.h"
Functions
void watchdog_config (void)
void watchdog_reset_counter (void)
void wdt_hold_counter (void)
void wdt_release_counter (void)
void reboot (void)
Function Documentation
watchdog_config()
void watchdog_config (void)
Definition at line 11 of file watchdog.c.
Referenced by config_msp430().
watchdog_reset_counter()
void watchdog_reset_counter (void)
Definition at line 15 of file watchdog.c.
Referenced by config_msp430(), timer0_a0_isr(), and timer0_a1_isr().
wdt_hold_counter()
void wdt_hold_counter (void)
Definition at line 21 of file watchdog.c.
wdt_release_counter()
void wdt_release_counter (void)
Definition at line 25 of file watchdog.c.
reboot()
void reboot (void)
Definition at line 29 of file watchdog.c.