FloripaSat-EPS: SPI.c File Reference
SPI.c File Reference
#include <msp430.h>
#include "SPI.h"
Functions
void spi_config (void)
void spi_send (int data)
int spi_read (void)
Function Documentation
spi_config()
void spi_config (void)
Definition at line 11 of file SPI.c.
Referenced by config_msp430().
spi_send()
void spi_send (int data)
Definition at line 24 of file SPI.c.
Referenced by config_ADS1248(), and read_ADS1248().
spi_read()
int spi_read (void)
Definition at line 30 of file SPI.c.
Referenced by config_ADS1248(), and read_ADS1248().