FloripaSat-EPS: mppt.h File Reference
mppt.h File Reference
#include <msp430.h>
#include "uart.h"
Data Structures
struct mppt_parameters_t
Macros
#define HWREG16(x) (*((volatile uint16_t *)((uint16_t)x)))
#define solar_panel_current_unit 0.0001479640152
#define solar_panel_voltage_unit 0.001178588867
Functions
void mppt_algorithm (uint16_t current, uint16_t voltage, uint16_t address, mppt_parameters_t *mppt_paremeters)
Macro Definition Documentation
HWREG16
#define HWREG16 (x) (*((volatile uint16_t *)((uint16_t)x)))
Definition at line 20 of file mppt.h.
solar_panel_current_unit
#define solar_panel_current_unit 0.0001479640152
Definition at line 22 of file mppt.h.
Referenced by mppt_algorithm().
solar_panel_voltage_unit
#define solar_panel_voltage_unit 0.001178588867
Definition at line 23 of file mppt.h.
Referenced by mppt_algorithm().
Function Documentation
mppt_algorithm()
void mppt_algorithm (uint16_t current, uint16_t voltage, uint16_t address, mppt_parameters_t * mppt_paremeters)
Definition at line 6 of file mppt.c.
References float_send(), HWREG16, mppt_parameters_t::previous_power, mppt_parameters_t::previous_step, mppt_parameters_t::previous_voltage, solar_panel_current_unit, solar_panel_voltage_unit, and uart_tx_debug().
Referenced by timer0_a1_isr().