FloripaSat-EPS: ADC.c File Reference
ADC.c File Reference
#include <msp430.h>
#include "ADC.h"
Functions
void adc_config (void)
int16_t adc_read (uint8_t channel)
Function Documentation
adc_config()
void adc_config (void)
Definition at line 8 of file ADC.c.
Referenced by config_msp430().
adc_read()
int16_t adc_read (uint8_t channel)
Definition at line 37 of file ADC.c.
Referenced by timer0_a0_isr(), and timer0_a1_isr().