FloripaSat-EPS: onewire.c File Reference
onewire.c File Reference
#include <msp430.h>
#include <stdio.h>
#include "onewire.h"
#include "intrinsics.h"
#include "uart.h"
Macros
#define clock 8000000
#define P_WireOUT P9OUT
#define P_WireIN P9IN
#define DIR_P_Wire P9DIR
#define BitWire BIT1
Functions
void outp (int bit)
int inp (void)
int OneWireReset (void)
void OneWireWrite (int bit)
int OneWireReadBit (void)
void OWWriteByte (int data)
uint8_t OWReadByte (void)
void config_DS2775 (void)
void measurement_data_DS2775 (void)
uint8_t DS2775_read_register (uint8_t register_address)
Variables
volatile int avc_msb =0x00
volatile int avc_lsb =0x00
volatile int vr_msb1 =0x00
volatile int vr_lsb1 =0x00
volatile int vr_msb2 =0x00
volatile int vr_lsb2 =0x00
volatile int tr_msb =0x00
volatile int tr_lsb =0x00
volatile int cr_msb =0x00
volatile int cr_lsb =0x00
volatile int acr_msb =0x00
volatile int acr_lsb =0x00
volatile unsigned int RG_Protection
unsigned char protection_register_msb = 0x00
unsigned char protection_register_lsb = 0x00
volatile unsigned int count = 0
Macro Definition Documentation
clock
#define clock 8000000
Definition at line 7 of file onewire.c.
Referenced by OneWireReadBit(), OneWireReset(), and OneWireWrite().
P_WireOUT
#define P_WireOUT P9OUT
Definition at line 9 of file onewire.c.
Referenced by outp().
P_WireIN
#define P_WireIN P9IN
Definition at line 10 of file onewire.c.
Referenced by inp().
DIR_P_Wire
#define DIR_P_Wire P9DIR
Definition at line 11 of file onewire.c.
Referenced by inp(), and outp().
BitWire
#define BitWire BIT1
Definition at line 12 of file onewire.c.
Referenced by inp(), and outp().
Function Documentation
outp()
void outp (int bit)
Definition at line 41 of file onewire.c.
References BitWire, DIR_P_Wire, and P_WireOUT.
Referenced by OneWireReadBit(), OneWireReset(), and OneWireWrite().
inp()
int inp (void)
Definition at line 61 of file onewire.c.
References BitWire, DIR_P_Wire, and P_WireIN.
Referenced by OneWireReadBit(), and OneWireReset().
OneWireReset()
int OneWireReset (void)
Definition at line 79 of file onewire.c.
References clock, inp(), and outp().
Referenced by config_DS2775(), DS2775_read_register(), and measurement_data_DS2775().
OneWireWrite()
void OneWireWrite (int bit)
Definition at line 106 of file onewire.c.
References clock, and outp().
Referenced by OWWriteByte().
OneWireReadBit()
int OneWireReadBit (void)
Definition at line 135 of file onewire.c.
References clock, inp(), and outp().
Referenced by OWReadByte().
OWWriteByte()
void OWWriteByte (int data)
Definition at line 158 of file onewire.c.
References OneWireWrite().
Referenced by config_DS2775(), DS2775_read_register(), and measurement_data_DS2775().
OWReadByte()
uint8_t OWReadByte (void)
Definition at line 178 of file onewire.c.
References OneWireReadBit().
Referenced by DS2775_read_register(), and measurement_data_DS2775().
config_DS2775()
void config_DS2775 (void)
Definition at line 195 of file onewire.c.
References accumulated_current_LSB_register, accumulated_current_MSB_register, control_register, current_gain_LSB_register, DS2775_read_register(), OneWireReset(), overcurrent_thresholds_register, OWWriteByte(), protection_register, protector_threshold_register, status_register, and uart_tx_debug().
Referenced by main().
measurement_data_DS2775()
void measurement_data_DS2775 (void)
Definition at line 302 of file onewire.c.
References accumulated_current_LSB_register, accumulated_current_MSB_register, acr_lsb, acr_msb, avc_lsb, avc_msb, average_current_LSB_register, average_current_MSB_register, control_register, cr_lsb, cr_msb, current_gain_LSB_register, current_LSB_register, current_MSB_register, OneWireReset(), overcurrent_thresholds_register, OWReadByte(), OWWriteByte(), protection_register, RG_Protection, temperature_LSB_register, temperature_MSB_register, tr_lsb, tr_msb, voltage_LSB1_register, voltage_LSB2_register, voltage_MSB1_register, voltage_MSB2_register, vr_lsb1, vr_lsb2, vr_msb1, and vr_msb2.
DS2775_read_register()
uint8_t DS2775_read_register (uint8_t register_address)
Definition at line 456 of file onewire.c.
References OneWireReset(), OWReadByte(), and OWWriteByte().
Referenced by config_DS2775(), and timer0_a0_isr().
Variable Documentation
avc_msb
volatile int avc_msb =0x00
Definition at line 14 of file onewire.c.
Referenced by measurement_data_DS2775().
avc_lsb
volatile int avc_lsb =0x00
Definition at line 15 of file onewire.c.
Referenced by measurement_data_DS2775().
vr_msb1
volatile int vr_msb1 =0x00
Definition at line 16 of file onewire.c.
Referenced by measurement_data_DS2775().
vr_lsb1
volatile int vr_lsb1 =0x00
Definition at line 17 of file onewire.c.
Referenced by measurement_data_DS2775().
vr_msb2
volatile int vr_msb2 =0x00
Definition at line 18 of file onewire.c.
Referenced by measurement_data_DS2775().
vr_lsb2
volatile int vr_lsb2 =0x00
Definition at line 19 of file onewire.c.
Referenced by measurement_data_DS2775().
tr_msb
volatile int tr_msb =0x00
Definition at line 20 of file onewire.c.
Referenced by measurement_data_DS2775().
tr_lsb
volatile int tr_lsb =0x00
Definition at line 21 of file onewire.c.
Referenced by measurement_data_DS2775().
cr_msb
volatile int cr_msb =0x00
Definition at line 22 of file onewire.c.
Referenced by measurement_data_DS2775().
cr_lsb
volatile int cr_lsb =0x00
Definition at line 23 of file onewire.c.
Referenced by measurement_data_DS2775().
acr_msb
volatile int acr_msb =0x00
Definition at line 24 of file onewire.c.
Referenced by measurement_data_DS2775().
acr_lsb
volatile int acr_lsb =0x00
Definition at line 25 of file onewire.c.
Referenced by measurement_data_DS2775().
RG_Protection
volatile unsigned int RG_Protection
Definition at line 27 of file onewire.c.
Referenced by measurement_data_DS2775().
protection_register_msb
unsigned char protection_register_msb = 0x00
Definition at line 29 of file onewire.c.
protection_register_lsb
unsigned char protection_register_lsb = 0x00
Definition at line 30 of file onewire.c.
count
volatile unsigned int count = 0
Definition at line 32 of file onewire.c.