FloripaSat-EPS: main.c File Reference
main.c File Reference
Main MCU and peripherals configuration.
#include <msp430.h>
#include <stdlib.h>
#include "ADC.h"
#include "ADS1248.h"
#include "I2C.h"
#include "onewire.h"
#include "pid.h"
#include "timer.h"
#include "uart.h"
#include "SPI.h"
#include "clock.h"
#include "hal.h"
#include "watchdog.h"
#include "fsp.h"
Functions
void config_msp430 (void)
void main (void)
Main Function.
Detailed Description
Main MCU and peripherals configuration.
Author
Bruno Vale Barbosa Eiterer bruno.nosp@m.eite.nosp@m.rer@g.nosp@m.mail.nosp@m..com
Definition in file main.c.
Function Documentation
config_msp430()
void config_msp430 (void)
Definition at line 68 of file main.c.
References adc_config(), clock_config(), I2C_config(), OBDH_TTC_regulator_enable_dir, OBDH_TTC_regulator_enable_pin, payload_regulator_enable_dir, payload_regulator_enable_pin, spi_config(), system_on_dir, system_on_pin, system_on_port, timer_config(), uart_config(), uart_tx_debug(), watchdog_config(), and watchdog_reset_counter().
Referenced by main().
main()
main (void)
Main Function.
Configures the MCU registers and other peripherals.
Definition at line 35 of file main.c.
References config_ADS1248(), config_DS2775(), config_msp430(), and uart_tx_debug().