FloripaSat-EPS: uart.h File Reference
uart.h File Reference
UART driver header.
#include <stdint.h>
Functions
void port_mapping (void)
Maps multi-function port 2 pins to UART.
void uart_config (void)
Configures the UART peripheral.
void uart_tx_debug (uint8_t *tx_data)
Sends data to the debug port.
void uart_tx_beacon (uint8_t tx_data)
Sends data to Beacon.
void float_send (float c)
Sends floating point data to the debug port.
Detailed Description
UART driver header.
Author
Bruno Vale Barbosa Eiterer
Definition in file uart.h.
Function Documentation
port_mapping()
void port_mapping (void)
Maps multi-function port 2 pins to UART.
First it enables write-access to the port mapping registers in the PMAPPWD register, then it chooses the UCA0TXD function in the P2MAP4 register, then it disables write-access to port mapping registers.
Parameters
-
Returns
-
Definition at line 120 of file uart.c.
Referenced by uart_config().
uart_config()
void uart_config (void)
Configures the UART peripheral.
The first step is to call port_mapping.
The first interface configuration done is the UCA2, used for debugging. First it assigns P9.2 to UCA2TXD and P9.3 to UCA2RXD. Then it sets the UCSWRST bit in the UCA2CTL1 register, allowing the configuration to start. Then it selects the ACLK (16 MHz) clock source in the UCA2CTL1 register. The baud rate is selected in the UCA2BR0 and UCA2BR1 registers, with values of 0x8A and 0x00, respectively. This results in 16000000/138 = ~115942 bps. Then the modulation is set in the UCA2MCTL, with UCBRS_7 + UCBRF_0, resulting in a baud rate close of 115200 bps. To finish the configuration the UCSWRST bit is cleared in the UCA2CTL1 register, resuming normal operation.
The second interface configuration done is the UCA0, used to communicate with Beacon. First it assigns P2.4 to UCA0TXD, then it sets the UCSWRST bit in the UCA0CTL1 register. The clock source used is also ACLK (16 MHz). The baud rate registers UCA0BR0 and UCA0BR1 are set wth 0xD0 and 0x00, respectively. In the UCA0MCTL register the modulation select is UCBRS_0 and UCBRF_5 with oversampling defined by UCOS16, resulting in a baud rate of ~4800 bps. Then it clears the UCSWRST bit as well, returning to normal operation.
Parameters
-
Returns
-
Definition at line 40 of file uart.c.
References port_mapping().
Referenced by config_msp430().
uart_tx_debug()
void uart_tx_debug (uint8_t * tx_data)
Sends data to the debug port.
This function sends a byte of data to the debug port. Before each bit is transmitted, it checks if the line is busy through the UCBUSY bit in the UCA2STAT register. Then it sends the bit by putting it in the UCA2TXBUF register. It loops until the end of the data is reached.
Parameters
tx_data is a pointer to the data to be sent.
Returns
-
Definition at line 76 of file uart.c.
Referenced by config_ADS1248(), config_DS2775(), config_msp430(), float_send(), main(), mppt_algorithm(), timer0_a0_isr(), and timer0_a1_isr().
uart_tx_beacon()
void uart_tx_beacon (uint8_t tx_data)
Sends data to Beacon.
Sends data to Beacon.
Sends a byte of data to Beacon. First it checks if the line is busy, using the UCBUSY bit in the UCA0STAT register. Then it places the data to be sent in the UCA0TXBUF register.
Parameters
tx_data is an unsigned integer of 8 bits, containing the data to be sent to Beacon
Returns
-
Definition at line 101 of file uart.c.
Referenced by timer0_a0_isr().
float_send()
void float_send (volatile float c)
Sends floating point data to the debug port.
First it verifies if the floating point number passed is negative, if it is it sends a "-" character, then inverts the number. Then it converts the number to a string, and passes the string to uart_tx_debug.
Parameters
c is the floating point number to be sent via UART.
Returns
-
Definition at line 143 of file uart.c.
References uart_tx_debug().
Referenced by mppt_algorithm(), timer0_a0_isr(), and timer0_a1_isr().