FloripaSat-EPS: onewire.h File Reference
onewire.h File Reference
#include <stdint.h>
Macros
#define protection_register 0x00
#define protector_threshold_register 0x7F
#define status_register 0x01
#define control_register 0x60
#define accumulated_current_MSB_register 0x10
#define accumulated_current_LSB_register 0x11
#define temperature_MSB_register 0x0A
#define temperature_LSB_register 0x0B
#define average_current_MSB_register 0x08
#define average_current_LSB_register 0x09
#define overcurrent_thresholds_register 0x78
#define current_gain_LSB_register 0x79
#define current_MSB_register 0x0E
#define current_LSB_register 0x0F
#define voltage_MSB1_register 0x0C
#define voltage_LSB1_register 0x0D
#define voltage_MSB2_register 0x1C
#define voltage_LSB2_register 0x1D
#define rsense 0.01
#define voltage_unit 0.004883
#define current_unit 0.0000015625/rsense
#define accumulated_current_unit 6.25*0.000001/rsense
Functions
void config_DS2775 (void)
void measurement_data_DS2775 (void)
void outp (int bit)
int inp (void)
int OneWireReset (void)
void OneWireWrite (int bit)
int OneWireReadBit (void)
void OWWriteByte (int data)
uint8_t OWReadByte (void)
uint8_t DS2775_read_register (uint8_t register_address)
Macro Definition Documentation
protection_register
#define protection_register 0x00
Definition at line 15 of file onewire.h.
Referenced by config_DS2775(), measurement_data_DS2775(), and timer0_a0_isr().
protector_threshold_register
#define protector_threshold_register 0x7F
Definition at line 16 of file onewire.h.
Referenced by config_DS2775().
status_register
#define status_register 0x01
Definition at line 17 of file onewire.h.
Referenced by config_DS2775().
control_register
#define control_register 0x60
Definition at line 18 of file onewire.h.
Referenced by config_DS2775(), and measurement_data_DS2775().
accumulated_current_MSB_register
#define accumulated_current_MSB_register 0x10
Definition at line 19 of file onewire.h.
Referenced by config_DS2775(), measurement_data_DS2775(), and timer0_a0_isr().
accumulated_current_LSB_register
#define accumulated_current_LSB_register 0x11
Definition at line 20 of file onewire.h.
Referenced by config_DS2775(), measurement_data_DS2775(), and timer0_a0_isr().
temperature_MSB_register
#define temperature_MSB_register 0x0A
Definition at line 21 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
temperature_LSB_register
#define temperature_LSB_register 0x0B
Definition at line 22 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
average_current_MSB_register
#define average_current_MSB_register 0x08
Definition at line 23 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
average_current_LSB_register
#define average_current_LSB_register 0x09
Definition at line 24 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
overcurrent_thresholds_register
#define overcurrent_thresholds_register 0x78
Definition at line 25 of file onewire.h.
Referenced by config_DS2775(), and measurement_data_DS2775().
current_gain_LSB_register
#define current_gain_LSB_register 0x79
Definition at line 26 of file onewire.h.
Referenced by config_DS2775(), and measurement_data_DS2775().
current_MSB_register
#define current_MSB_register 0x0E
Definition at line 27 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
current_LSB_register
#define current_LSB_register 0x0F
Definition at line 28 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
voltage_MSB1_register
#define voltage_MSB1_register 0x0C
Definition at line 29 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
voltage_LSB1_register
#define voltage_LSB1_register 0x0D
Definition at line 30 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
voltage_MSB2_register
#define voltage_MSB2_register 0x1C
Definition at line 31 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
voltage_LSB2_register
#define voltage_LSB2_register 0x1D
Definition at line 32 of file onewire.h.
Referenced by measurement_data_DS2775(), and timer0_a0_isr().
rsense
#define rsense 0.01
Definition at line 36 of file onewire.h.
voltage_unit
#define voltage_unit 0.004883
Definition at line 37 of file onewire.h.
Referenced by timer0_a0_isr().
current_unit
#define current_unit 0.0000015625/rsense
Definition at line 38 of file onewire.h.
Referenced by timer0_a0_isr().
accumulated_current_unit
#define accumulated_current_unit 6.25*0.000001/rsense
Definition at line 39 of file onewire.h.
Referenced by timer0_a0_isr().
Function Documentation
config_DS2775()
void config_DS2775 (void)
Definition at line 195 of file onewire.c.
References accumulated_current_LSB_register, accumulated_current_MSB_register, control_register, current_gain_LSB_register, DS2775_read_register(), OneWireReset(), overcurrent_thresholds_register, OWWriteByte(), protection_register, protector_threshold_register, status_register, and uart_tx_debug().
Referenced by main().
measurement_data_DS2775()
void measurement_data_DS2775 (void)
Definition at line 302 of file onewire.c.
References accumulated_current_LSB_register, accumulated_current_MSB_register, acr_lsb, acr_msb, avc_lsb, avc_msb, average_current_LSB_register, average_current_MSB_register, control_register, cr_lsb, cr_msb, current_gain_LSB_register, current_LSB_register, current_MSB_register, OneWireReset(), overcurrent_thresholds_register, OWReadByte(), OWWriteByte(), protection_register, RG_Protection, temperature_LSB_register, temperature_MSB_register, tr_lsb, tr_msb, voltage_LSB1_register, voltage_LSB2_register, voltage_MSB1_register, voltage_MSB2_register, vr_lsb1, vr_lsb2, vr_msb1, and vr_msb2.
outp()
void outp (int bit)
Definition at line 41 of file onewire.c.
References BitWire, DIR_P_Wire, and P_WireOUT.
Referenced by OneWireReadBit(), OneWireReset(), and OneWireWrite().
inp()
int inp (void)
Definition at line 61 of file onewire.c.
References BitWire, DIR_P_Wire, and P_WireIN.
Referenced by OneWireReadBit(), and OneWireReset().
OneWireReset()
int OneWireReset (void)
Definition at line 79 of file onewire.c.
References clock, inp(), and outp().
Referenced by config_DS2775(), DS2775_read_register(), and measurement_data_DS2775().
OneWireWrite()
void OneWireWrite (int bit)
Definition at line 106 of file onewire.c.
References clock, and outp().
Referenced by OWWriteByte().
OneWireReadBit()
int OneWireReadBit (void)
Definition at line 135 of file onewire.c.
References clock, inp(), and outp().
Referenced by OWReadByte().
OWWriteByte()
void OWWriteByte (int data)
Definition at line 158 of file onewire.c.
References OneWireWrite().
Referenced by config_DS2775(), DS2775_read_register(), and measurement_data_DS2775().
OWReadByte()
uint8_t OWReadByte (void)
Definition at line 178 of file onewire.c.
References OneWireReadBit().
Referenced by DS2775_read_register(), and measurement_data_DS2775().
DS2775_read_register()
uint8_t DS2775_read_register (uint8_t register_address)
Definition at line 456 of file onewire.c.
References OneWireReset(), OWReadByte(), and OWWriteByte().
Referenced by config_DS2775(), and timer0_a0_isr().