FloripaSat-EPS: watchdog.h File Reference
watchdog.h File Reference
#include <msp430.h>
Macros
#define INTERVAL 0x10
#define WATCHDOG 0x00
#define _1_2_SEC 0x04
#define _188_mSEC 0x05
#define _11_8_mSEC 0x06
#define _4_1_mSEC 0x00
#define _1_5_mSEC 0x07
#define _1_mSEC 0x01
#define _64_uSEC 0x02
#define _8_uSEC 0x03
Functions
void watchdog_config ()
void watchdog_reset_counter (void)
void wdt_hold_counter (void)
void reboot (void)
Macro Definition Documentation
INTERVAL
#define INTERVAL 0x10
Definition at line 14 of file watchdog.h.
WATCHDOG
#define WATCHDOG 0x00
Definition at line 15 of file watchdog.h.
_1_2_SEC
#define _1_2_SEC 0x04
Definition at line 18 of file watchdog.h.
_188_mSEC
#define _188_mSEC 0x05
Definition at line 19 of file watchdog.h.
_11_8_mSEC
#define _11_8_mSEC 0x06
Definition at line 20 of file watchdog.h.
_4_1_mSEC
#define _4_1_mSEC 0x00
Definition at line 21 of file watchdog.h.
_1_5_mSEC
#define _1_5_mSEC 0x07
Definition at line 22 of file watchdog.h.
_1_mSEC
#define _1_mSEC 0x01
Definition at line 23 of file watchdog.h.
_64_uSEC
#define _64_uSEC 0x02
Definition at line 24 of file watchdog.h.
_8_uSEC
#define _8_uSEC 0x03
Definition at line 25 of file watchdog.h.
Function Documentation
watchdog_config()
void watchdog_config ()
Definition at line 11 of file watchdog.c.
Referenced by config_msp430().
watchdog_reset_counter()
void watchdog_reset_counter (void)
Definition at line 15 of file watchdog.c.
Referenced by config_msp430(), timer0_a0_isr(), and timer0_a1_isr().
wdt_hold_counter()
void wdt_hold_counter (void)
Definition at line 21 of file watchdog.c.
reboot()
void reboot (void)
Definition at line 29 of file watchdog.c.