FloripaSat-EPS: ADS1248.c File Reference
ADS1248.c File Reference
#include "ADS1248.h"
Functions
void config_ADS1248 (uint8_t positive_channel)
int32_t read_ADS1248 (uint8_t channel)
Function Documentation
config_ADS1248()
void config_ADS1248 (uint8_t positive_channel)
Definition at line 19 of file ADS1248.c.
References ADS1248_START_pin, ADS1248_START_port, chip_select_pin, chip_select_port, negative_channel, NOP_command, RESET_command, RREG_command, SDATAC_command, spi_read(), spi_send(), uart_tx_debug(), and WREG_command.
Referenced by main().
read_ADS1248()
int32_t read_ADS1248 (uint8_t channel)
Definition at line 96 of file ADS1248.c.
References chip_select_pin, chip_select_port, negative_channel, NOP_command, RDATA_command, SDATAC_command, spi_read(), spi_send(), SYNC_command, temp, and WREG_command.
Referenced by timer0_a0_isr().